# Generated by Django 4.1.2 on 2022-12-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_companyOwner',
            field=models.BooleanField(default=False),
        ),
    ]
