# Generated by Django 4.1.2 on 2022-11-15 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('main_front', models.CharField(max_length=255)),
                ('main_back', models.CharField(max_length=255)),
                ('available_places', models.IntegerField(default=0)),
                ('places', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
