# Generated by Django 4.1.2 on 2022-11-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_is_company_useraccount_is_leader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('main_front', models.CharField(max_length=255)),
                ('main_back', models.CharField(max_length=255)),
                ('available_places', models.IntegerField(default=0)),
                ('places', models.IntegerField()),
            ],
        ),
    ]
