# Generated by Django 4.1.2 on 2022-11-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='available_places',
            field=models.IntegerField(default=0),
        ),
    ]
