# Generated by Django 4.1.2 on 2022-11-21 15:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_company_available_places'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='available_places',
            new_name='occupied_places',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('occupied_places', models.IntegerField(default=0)),
                ('places', models.IntegerField()),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('completion_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
