# Generated by Django 4.1.2 on 2022-11-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_available_places_company_occupied_places_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.team'),
        ),
    ]
