# Generated by Django 4.1.2 on 2022-11-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraccount_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='completion_date',
            field=models.DateField(null=True),
        ),
    ]
