# Generated by Django 4.1.2 on 2022-11-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_team_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='membership',
        ),
    ]
